language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - coverage run --source="storjkademlia" setup.py test

after_success:
  - coveralls
